apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: tax-calculator-pipeline-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  workspaces:
    - name: pipeline-workspace
      emptyDir: {}
  params:
    - name: repo-url
      value: https://github.com/jawariaqazi585-ai/zntwk-tax_calculator.git
    - name: imageUrl
      value: us.icr.io/sn-labs-jawariaqazi5/tax-calculator
    - name: imageTag
      value: "1.0"
